package com.lwazi.ws.trainings;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-10-28T17:25:24.821+02:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://trainings.ws.lwazi.com/", name = "CustomerOrdersPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerOrdersPortType {

    @WebMethod
    @WebResult(name = "getOrdersResponse", targetNamespace = "http://trainings.ws.lwazi.com/", partName = "parameters")
    public GetOrdersResponse getOrders(

        @WebParam(partName = "parameters", name = "getOrdersRequest", targetNamespace = "http://trainings.ws.lwazi.com/")
        GetOrdersRequest parameters
    );

    @WebMethod
    @WebResult(name = "createOrdersResponse", targetNamespace = "http://trainings.ws.lwazi.com/", partName = "parameters")
    public CreateOrdersResponse createOrders(

        @WebParam(partName = "parameters", name = "createOrdersRequest", targetNamespace = "http://trainings.ws.lwazi.com/")
        CreateOrdersRequest parameters
    );
}
