package com.lwazi.ws.trainings;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-10-28T17:25:24.908+02:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "CustomerOrdersService",
                  wsdlLocation = "file:/C:/Users/User/Code4/Java%20Web%20Services/wsldFirstWebService/src/main/resources/wsdl/CustomerOrders.wsdl",
                  targetNamespace = "http://trainings.ws.lwazi.com/")
public class CustomerOrdersService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://trainings.ws.lwazi.com/", "CustomerOrdersService");
    public final static QName CustomerOrdersPort = new QName("http://trainings.ws.lwazi.com/", "CustomerOrdersPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/User/Code4/Java%20Web%20Services/wsldFirstWebService/src/main/resources/wsdl/CustomerOrders.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerOrdersService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/User/Code4/Java%20Web%20Services/wsldFirstWebService/src/main/resources/wsdl/CustomerOrders.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerOrdersService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerOrdersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerOrdersService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerOrdersService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerOrdersService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerOrdersService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerOrdersPortType
     */
    @WebEndpoint(name = "CustomerOrdersPort")
    public CustomerOrdersPortType getCustomerOrdersPort() {
        return super.getPort(CustomerOrdersPort, CustomerOrdersPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerOrdersPortType
     */
    @WebEndpoint(name = "CustomerOrdersPort")
    public CustomerOrdersPortType getCustomerOrdersPort(WebServiceFeature... features) {
        return super.getPort(CustomerOrdersPort, CustomerOrdersPortType.class, features);
    }

}
